"""
Cookie Manager: JSON and Netscape formats parsing, export, validation, and storage.
Handles #HttpOnly_ prefixes, float expiration dates, whitespace tolerances, and format conversions.
"""
import json
import re
from pathlib import Path
from typing import List, Dict, Any, Optional

def parse_netscape_cookies(text: str) -> List[Dict[str, Any]]:
    """
    Parses standard Netscape HTTP Cookie file format into list of cookie dicts.
    Format: domain, flag, path, secure, expiration, name, value
    Also handles #HttpOnly_ domain prefix without skipping.
    """
    cookies = []
    lines = text.strip().splitlines()
    for line in lines:
        line = line.strip()
        if not line:
            continue

        http_only = False
        if line.startswith("#HttpOnly_"):
            http_only = True
            line = line[len("#HttpOnly_"):].strip()
        elif line.startswith("#"):
            continue

        # Split by tabs or multiple spaces
        parts = re.split(r"\t+|\s{2,}", line)
        if len(parts) < 7:
            # Fallback single tab split
            parts = line.split("\t")

        if len(parts) >= 7:
            domain, include_subdomains, path, secure, expiration, name, value = parts[:7]
            try:
                exp_int = int(float(expiration))
            except (ValueError, TypeError):
                exp_int = 0

            cookies.append({
                "name": name.strip(),
                "value": value.strip(),
                "domain": domain.strip(),
                "path": path.strip() or "/",
                "expires": exp_int,
                "secure": secure.strip().lower() == "true",
                "httpOnly": http_only or (include_subdomains.strip().lower() == "true" and not domain.startswith("."))
            })
    return cookies

def cookies_to_netscape(cookies: List[Dict[str, Any]]) -> str:
    """
    Converts list of cookie objects to Netscape format.
    """
    lines = ["# Netscape HTTP Cookie File", "# Generated by Nazak Browser Studio", ""]
    for c in cookies:
        if not isinstance(c, dict):
            continue
        domain = str(c.get("domain", "")).strip()
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = str(c.get("path", "/")).strip() or "/"
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        
        raw_exp = c.get("expires") or c.get("expirationDate") or 0
        try:
            expires = str(int(float(raw_exp)))
        except (ValueError, TypeError):
            expires = "0"
            
        name = str(c.get("name", "")).strip()
        value = str(c.get("value", "")).strip()
        
        prefix = "#HttpOnly_" if c.get("httpOnly", False) else ""
        lines.append(f"{prefix}{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines)

def parse_any_cookies(raw_text: str) -> List[Dict[str, Any]]:
    """
    Parses JSON array or Netscape formatted cookies automatically with field normalization.
    """
    if not raw_text:
        return []
    text = raw_text.strip()
    if text.startswith("[") or text.startswith("{"):
        try:
            data = json.loads(text)
            if isinstance(data, dict):
                data = [data]
            if isinstance(data, list):
                sanitized = []
                for item in data:
                    if isinstance(item, dict) and item.get("name"):
                        sanitized.append({
                            "name": str(item.get("name", "")),
                            "value": str(item.get("value", "")),
                            "domain": str(item.get("domain", "")),
                            "path": str(item.get("path", "/")),
                            "expires": int(float(item.get("expirationDate") or item.get("expires") or 0)),
                            "secure": bool(item.get("secure", False)),
                            "httpOnly": bool(item.get("httpOnly", False))
                        })
                if sanitized:
                    return sanitized
        except Exception:
            pass
    return parse_netscape_cookies(text)
